### ISSUE TITLE
No reference to source code included

### ISSUE THREAD

**Issue by ethus3h** [mono/linux-packaging-referenceassemblies-pcl#1]
Source code for this part of Mono does not appear to be provided here, despite Mono [being MIT-licensed](http://www.mono-project.com/FAQ:_Licensing). This is preventing me packaging and using several packages that depend on this part of Mono... Thanks for your help.

**Comment by akoeplinger** [comment]
Correct, we unfortunately don't have the sources ourselves. PCL was superseded by .NET Standard which is fully open source, I'd suggest moving over to it.

**Comment by ethus3h** [comment]
Ok, thanks for the info!
